version: '3.8'  # Using newer version for security features

services:
  keycrafter-ssh:
    build: .
    ports:
      - "127.0.0.1:2222:22"  # Only bind to localhost
    volumes:
      - ./authorized_keys/authorized_keys:/home/download/.ssh/authorized_keys:ro  # Read-only mount
    restart: unless-stopped
    # Security configurations
    security_opt:
      - no-new-privileges:true  # Prevent privilege escalation
      - seccomp:security-policy.json  # Use our custom seccomp profile
    cap_drop:
      - ALL  # Drop all capabilities
    cap_add:
      - CHOWN  # Minimal capabilities needed for SFTP
      - SETUID
      - SETGID
      - DAC_OVERRIDE
    read_only: true  # Make container filesystem read-only
    tmpfs:  # Temporary filesystem for runtime needs
      - /tmp:size=100M,noexec
      - /var/run:size=100M
      - /var/log:size=100M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Resource limits
    mem_limit: 256M
    memswap_limit: 512M
    pids_limit: 50
    cpus: 0.5
    # Network isolation
    networks:
      - sftp_net
    # User namespace mapping
    userns_mode: "host"  # Use host's user namespace mapping

networks:
  sftp_net:
    driver: bridge
    internal: false  # Allow external access but only through exposed ports
    driver_opts:
      com.docker.network.bridge.name: br-keycrafter
    ipam:
      config:
        - subnet: 172.28.0.0/16
    # Network security options
    attachable: false
    enable_ipv6: false 