version: '3.8'  # Using newer version for security features

services:
  keycrafter-web:
    build: .
    volumes:
      - ./target/release/keycrafter.exe:/usr/share/nginx/downloads/keycrafter-windows-x64.exe
      - ./target/release/keycrafter:/usr/share/nginx/downloads/keycrafter-linux-x64
      - ./scripts/install.ps1:/usr/share/nginx/downloads/install.ps1
      - ./scripts/install.sh:/usr/share/nginx/downloads/install.sh
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web:/usr/share/nginx/html
    networks:
      sftp_net:
        ipv4_address: 172.28.0.2
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    networks:
      sftp_net:
        ipv4_address: 172.28.0.3
    volumes:
      - ./cloudflared:/etc/cloudflared:ro
    command: tunnel --config /etc/cloudflared/config.yml run
    restart: unless-stopped
    depends_on:
      - keycrafter-web

volumes:
  cloudflared-creds:

networks:
  sftp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
    # Network security options
    attachable: false
    enable_ipv6: false 